#!/bin/bash
for i in 1
do 
j=0
for n in ls FileList/PhaseII4/B_14TEV_HT${i}_140PileUp_*
do
echo '#!/bin/bash'>B-run-qsub${i}_0${j}.sh
echo 'source ~cmssoft/shrc' >>B-run-qsub${i}_0${j}.sh
echo 'cd ~/CMSSW_5_2_6/'>>B-run-qsub${i}_0${j}.sh
echo 'eval `scramv1 runtime -sh`'>>B-run-qsub${i}_0${j}.sh
echo 'cd src/StopCoannihilation_PhaseII4'>>B-run-qsub${i}_0${j}.sh
echo ' export LD_LIBRARY_PATH=/home/borzou/CMSSW_5_2_6/src/StopCoannihilation_PhaseII4/Delphes:$LD_LIBRARY_PATH;' >> B-run-qsub${i}_0${j}.sh
echo 'export X509_USER_PROXY=~/.x509_user_proxy' >> B-run-qsub${i}_0${j}.sh
if [ $j -lt 10 ]
then
echo "./main \"140PileUp\" \"B_14TEV_HT"${i}"\" \"PhaseII4\" \"Results\" \"0"$j"\""  >> B-run-qsub${i}_0${j}.sh
else
echo "./main \"140PileUp\" \"B_14TEV_HT"${i}"\" \"PhaseII4\" \"Results\" \""$j"\""  >> B-run-qsub${i}_0${j}.sh
fi

qsub -N B ./B-run-qsub${i}_0${j}.sh
sleep 5;
j=$(($j+1));
done
done
