#!/bin/bash
for i in {1..7}
do 
j=0
for n in ls FileList/PhaseII4/BJ_14TEV_HT${i}_140PileUp_*
do
echo '#!/bin/bash'>BJ-run-qsub${i}_0${j}.sh
echo 'source ~cmssoft/shrc' >>BJ-run-qsub${i}_0${j}.sh
echo 'cd ~/CMSSW_5_2_6/'>>BJ-run-qsub${i}_0${j}.sh
echo 'eval `scramv1 runtime -sh`'>>BJ-run-qsub${i}_0${j}.sh
echo 'cd src/StopCoannihilation_PhaseII4'>>BJ-run-qsub${i}_0${j}.sh
echo ' export LD_LIBRARY_PATH=/home/borzou/CMSSW_5_2_6/src/StopCoannihilation_PhaseII4/Delphes:$LD_LIBRARY_PATH;' >> BJ-run-qsub${i}_0${j}.sh
echo 'export X509_USER_PROXY=~/.x509_user_proxy' >> BJ-run-qsub${i}_0${j}.sh
if [ $j -lt 10 ]
then
echo "./main \"140PileUp\" \"BJ_14TEV_HT"${i}"\" \"PhaseII4\" \"Results\" \"0"$j"\""  >> BJ-run-qsub${i}_0${j}.sh
else
echo "./main \"140PileUp\" \"BJ_14TEV_HT"${i}"\" \"PhaseII4\" \"Results\" \""$j"\""  >> BJ-run-qsub${i}_0${j}.sh
fi

qsub -N BJ ./BJ-run-qsub${i}_0${j}.sh
sleep 5;
j=$(($j+1));
done
done
