#!/bin/bash
for i in {1..4}
do 
j=0
for n in ls FileList/PhaseI/BJJ_14TEV_HT${i}_50PileUp_*
do
echo '#!/bin/bash'>BJJ-run-qsub${i}_0${j}.sh
echo 'source ~cmssoft/shrc' >>BJJ-run-qsub${i}_0${j}.sh
echo 'cd ~/CMSSW_5_2_6/'>>BJJ-run-qsub${i}_0${j}.sh
echo 'eval `scramv1 runtime -sh`'>>BJJ-run-qsub${i}_0${j}.sh
echo 'cd src/StopCoannihilation_PhaseII4'>>BJJ-run-qsub${i}_0${j}.sh
echo ' export LD_LIBRARY_PATH=/home/borzou/CMSSW_5_2_6/src/StopCoannihilation_PhaseII4/Delphes:$LD_LIBRARY_PATH;' >> BJJ-run-qsub${i}_0${j}.sh
echo 'export X509_USER_PROXY=~/.x509_user_proxy' >> BJJ-run-qsub${i}_0${j}.sh
if [ $j -lt 10 ]
then
echo "./main \"50PileUp\" \"BJJ_14TEV_HT"${i}"\" \"PhaseI\" \"Results\" \"0"$j"\""  >> BJJ-run-qsub${i}_0${j}.sh
else
echo "./main \"50PileUp\" \"BJJ_14TEV_HT"${i}"\" \"PhaseI\" \"Results\" \""$j"\""  >> BJJ-run-qsub${i}_0${j}.sh
fi

qsub -N BJJ ./BJJ-run-qsub${i}_0${j}.sh
sleep 5;
j=$(($j+1));
done
done
