#!/bin/bash
for i in {1..7}
do 
j=0
for n in ls FileList/PhaseII4/FullExceptStopv4_14TEV_140PileUp_*
do
echo '#!/bin/bash'>FullEx-run-qsub${i}_0${j}.sh
echo 'source ~cmssoft/shrc' >>FullEx-run-qsub${i}_0${j}.sh
echo 'cd ~/CMSSW_5_2_6/'>>FullEx-run-qsub${i}_0${j}.sh
echo 'eval `scramv1 runtime -sh`'>>FullEx-run-qsub${i}_0${j}.sh
echo 'cd src/StopCoannihilation_PhaseII4'>>FullEx-run-qsub${i}_0${j}.sh
echo ' export LD_LIBRARY_PATH=/home/borzou/CMSSW_5_2_6/src/StopCoannihilation_PhaseII4/Delphes:$LD_LIBRARY_PATH;' >> FullEx-run-qsub${i}_0${j}.sh
echo 'export X509_USER_PROXY=~/.x509_user_proxy' >> FullEx-run-qsub${i}_0${j}.sh
if [ $j -lt 10 ]
then
echo "./main \"140PileUp\" \"FullExceptStopv4_14TEV\" \"PhaseII4\" \"Results\" \"0"$j"\""  >> FullEx-run-qsub${i}_0${j}.sh
else
echo "./main \"140PileUp\" \"FullExceptStopv4_14TEV\" \"PhaseII4\" \"Results\" \""$j"\""  >> FullEx-run-qsub${i}_0${j}.sh
fi

qsub -N stoc ./FullEx-run-qsub${i}_0${j}.sh
sleep 10;
j=$(($j+1));
done
done
