#!/bin/bash
for i in {1..5}
do 
j=0
for n in ls FileList/PhaseII4/TB_14TEV_HT${i}_140PileUp_*
do
echo '#!/bin/bash'>TB-run-qsub${i}_0${j}.sh
echo 'source ~cmssoft/shrc' >>TB-run-qsub${i}_0${j}.sh
echo 'cd ~/CMSSW_5_2_6/'>>TB-run-qsub${i}_0${j}.sh
echo 'eval `scramv1 runtime -sh`'>>TB-run-qsub${i}_0${j}.sh
echo 'cd src/StopCoannihilation_PhaseII4'>>TB-run-qsub${i}_0${j}.sh
echo ' export LD_LIBRARY_PATH=/home/borzou/CMSSW_5_2_6/src/StopCoannihilation_PhaseII4/Delphes:$LD_LIBRARY_PATH;' >> TB-run-qsub${i}_0${j}.sh
echo 'export X509_USER_PROXY=~/.x509_user_proxy' >> TB-run-qsub${i}_0${j}.sh
if [ $j -lt 10 ]
then
echo "./main \"140PileUp\" \"TB_14TEV_HT"${i}"\" \"PhaseII4\" \"Results\" \"0"$j"\""  >> TB-run-qsub${i}_0${j}.sh
else
echo "./main \"140PileUp\" \"TB_14TEV_HT"${i}"\" \"PhaseII4\" \"Results\" \""$j"\""  >> TB-run-qsub${i}_0${j}.sh
fi

qsub -N TB ./TB-run-qsub${i}_0${j}.sh
sleep 5;
j=$(($j+1));
done
done
